apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-apps
  template:
    metadata:
      labels:
        app: nginx-apps
    spec:
      containers:
      - name: nginx-containers
        image: nginx
