apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-apps
spec:
  selector:
    app: nginx-apps
  type: NodePort   #type of the service
  ports:
  - nodePort: 31000   #we can specify manually or k8's will provide random port from 30000-32676
    port: 80
    targetPort: 80 #container port #generally port and targetport are same.  
